### ISSUE TITLE
Compile fails: No instance for (Show (ℝ2 -> ℝ))

### ISSUE THREAD

**Issue by nbaum** [colah/ImplicitCAD#102]
I get the following output when running `cabal install`.

    $ cabal install
    Resolving dependencies...
    Configuring implicit-0.0.3...
    Building implicit-0.0.3...
    Preprocessing library implicit-0.0.3...
    [ 1 of 45] Compiling Graphics.Implicit.Export.Render.GetLoops ( Graphics/Implicit/Export/Render/GetLoops.hs, dist/build/Graphics/Implicit/Export/Render/GetLoops.o ) [flags changed]
    [ 2 of 45] Compiling Graphics.Implicit.Definitions ( Graphics/Implicit/Definitions.hs, dist/build/Graphics/Implicit/Definitions.o )

    Graphics/Implicit/Definitions.hs:113:18:
        No instance for (Show (ℝ2 -> ℝ))
          arising from the 'deriving' clause of a data type declaration
        Possible fix:
          add an instance declaration for (Show (ℝ2 -> ℝ))
          or use a standalone 'deriving instance' declaration,
               so you can specify the instance context yourself
        When deriving the instance for (Show SymbolicObj2)

    Graphics/Implicit/Definitions.hs:154:18:
        No instance for (Show (ℝ2 -> ℝ))
          arising from the 'deriving' clause of a data type declaration
        Possible fix:
          add an instance declaration for (Show (ℝ2 -> ℝ))
          or use a standalone 'deriving instance' declaration,
               so you can specify the instance context yourself
        When deriving the instance for (Show SymbolicObj3)
    Failed to install implicit-0.0.3
    cabal: Error: some packages failed to install:
    implicit-0.0.3 failed during the building phase. The exception was:
    ExitFailure 1

**Comment by mmachenry** [comment]
Duplicate has been closed. I'm closing this issue.
