### ISSUE TITLE
Juicy Pixels 3.1 fails to build on OSX 10.7.5 / Cabal 0.10.2

### ISSUE THREAD

**Issue by D1plo1d** [colah/ImplicitCAD#105]
ImplicitCAD fails to install on OSX because of a Juicy Pixel issue.

This is what I see in the console: https://gist.github.com/D1plo1d/6819376

**Comment by julialongtin** [comment]
Closing issue. Sorry, but i don't have OSX to test against, nor do i have enough deep haskell knowlege to even know what that error is. ;)
