### ISSUE TITLE
Non-exhaustive patterns in case

### ISSUE THREAD

**Issue by canadaduane** [colah/ImplicitCAD#109]
I feel like I must be doing something silly, but when I compile and run extopenscad, I get the following errors:

```
Macintosh:ImplicitCAD duane$ extopenscad -o test.svg <(cat <<-SCAD
union() {
    square([80,80]);
    translate ([80,80]) circle(30);
}
SCAD)
extopenscad: extopenscad.hs:(122,25)-(136,48): Non-exhaustive patterns in case

Macintosh:ImplicitCAD duane$ subl .
Macintosh:ImplicitCAD duane$ extopenscad <(cat <<-SCAD
union() {
    square([80,80]);
    translate ([80,80]) circle(30);
}
SCAD)
Rendering 2D object to /dev/fd/63.svg
UnionR2 0.0 [RectR 0.0 (0.0,0.0) (80.0,80.0),Translate2 (80.0,80.0) (Circle 30.0)]
extopenscad: /dev/fd/63.svg: openFile: does not exist (No such file or directory)
```

In the first case, I'm not sure why it is unable to detect the "svg" type ("Non-exhaustive patterns in case").

In the second case, I don't understand why it is trying to save to /dev/fd/*.svg by default.

I'm running on Mac OS X 10.9. I was originally using clang, but switched to gcc4.2.

**Comment by julialongtin** [comment]
strange. have you tried the newest version?

**Comment by canadaduane** [comment]
Works now
