### ISSUE TITLE
Pass parameters that get defined as variables?

### ISSUE THREAD

**Issue by eddieparker** [colah/ImplicitCAD#112]
In openscad you can pass parameters through -D in the command line, I believe.  I can't seem to see something similar in extopenscad.  It would be nice to be able to build a 'customizer' UI for this external to the tool, that updates the variables.

**Comment by julialongtin** [comment]
https://github.com/colah/ImplicitCAD/commit/8ded114e78d50f7cc0740fde20c69b9726a22403

Feature Implemented in master, exactly like requested. Closing issue.
