### ISSUE TITLE
Faceting on edges of cylinders

### ISSUE THREAD

**Issue by eddieparker** [colah/ImplicitCAD#113]
I'm trying out ImplicitCAD for the first time, and noticing that the quality of the renders is less precise than OpenSCAD.  I'm not sure if I'm doing something wrong however on my side.

I've attached a sample .scad file, the .stl it generates.  This is with a resolution of .125 - it's much worse if I don't set anything on the command line.
![faceting](https://cloud.githubusercontent.com/assets/1141487/3635678/1467a452-0f84-11e4-9da7-2bd0b985e903.png)

Is this to be expected?  OpenSCAD doesn't have the chunkiness - for comparison it renders the model like this: 
![openscad](https://cloud.githubusercontent.com/assets/1141487/3635682/729fb280-0f84-11e4-9a6d-f5ee194e5f54.png)

scad file:

```
gQuality=200;
gMetricScrewSize=3;
gBedHeight=4.4;
gClipHeightAboveBed=3.25;
gScrewWallThickness=5;
gClipLength=12;

screwRadius=gMetricScrewSize/2*1.1;
outerScrewRadius=screwRadius+gScrewWallThickness/2;
totalHeight=gClipHeightAboveBed+gBedHeight;

difference()
{
    union()
    {
        translate([-outerScrewRadius,0,0])
        cube([outerScrewRadius*2,gClipLength,gClipHeightAboveBed]);
        cylinder(r=outerScrewRadius,h=totalHeight, $fn=gQuality);
    }
    cylinder(r=screwRadius,h=totalHeight, $fn=gQuality);
}
```

**Comment by wbrickner** [comment]
was anyone able to get to the bottom of this?
It's a really big problem!

I don't use haskell and I dont understand exactly how ImplicitCAD works, so I can't work on fixing it.

Could someone please try to find the problem?

**Comment by TLC123** [comment]
The edge artifacts looks like what is expected when generating a mesh with marching cubes, more precise algorithms exist but are not implemented in ImplicitCAD. For example  [Antimonys ](https://goo.gl/fjkO6z).stl export includes feature detection to preserve corners and edges sharp.  Here's a technical paper [https://www.graphics.rwth-aachen.de/media/papers/feature1.pdf](https://www.graphics.rwth-aachen.de/media/papers/feature1.pdf)

**Comment by julialongtin** [comment]
expected behavior. for 3d printing, i just set the -r option to my layer height, and none of that is visible in the printed part.
