### ISSUE TITLE
makefile doesn't find libraries installed through cabal

### ISSUE THREAD

**Issue by sudoman** [colah/ImplicitCAD#119]
```
$ cabal list optparse
* optparse-applicative
    Synopsis: Utilities and combinators for parsing command line options
    Default available version: 0.11.0.1
    Installed versions: 0.9.1.1
    Homepage: https://github.com/pcapriotti/optparse-applicative
    License:  BSD3

$ make
./Setup configure --prefix=$PREFIX
Configuring implicit-0.0.3...
Setup: At least the following dependencies are missing:
optparse-applicative >=0.9.0.0 && <0.10.0, storable-endian -any
Makefile:9: recipe for target 'dist/setup-config' failed
make: *** [dist/setup-config] Error 1
```

the other packages were installed through debian jessie repos, however the version of optparse-applicative was too new, so i had installed it through cabal. i tried `cabal install optparse-applicative\<0.10.0` and `sudo cabal install optparse-applicative\<0.10.0`.

the other installation method of "cabal configure && cabal install" worked fine. what about a makefile that executes `cabal` commands instead?

**Comment by firegurafiku** [comment]
BTW, what's for the Makefile is kept there? Isn't `make command` anything better than `cabal command`?

**Comment by mmachenry** [comment]
I really don't know. :) It appears to just be shorthand for people are more used to make than cabal.

**Comment by julialongtin** [comment]
I'm a C programmer first. Make just makes sense to me. can you perform this test again with the current version?
