### ISSUE TITLE
no new release in the last two years

### ISSUE THREAD

**Issue by sudoman** [colah/ImplicitCAD#120]
how about making a new release of ImplicitCAD and uploading it to hackage? In your ccc talk, it sounds like you did a lot of work in that time period. :-)

**Comment by mmachenry** [comment]
Chris is currently busy with other things and not working on ImplicitCAD. I have requested Hackage maintenance permissions to address this issue and I'll be taking over managing pull requests.

**Comment by krakrjak** [comment]
So what's the plan on making a 0.0.4 or 0.1.0 release?  I'd really love to just be able to use the version from hackage again soon.

**Comment by junjihashimoto** [comment]
Me too.(I want to use this from hackage.)

**Comment by mmachenry** [comment]
I am going away on a vacation for two weeks where I won't have electricity or cell phone towers. Sorry for the delay, this trip has time-consuming preparation. Immediately after I get back I will be putting something up on Hackage. In the meantime you can currently compile the head revision on GitHub with GHC 7.10. In other news, we're working on getting the website rendering back up and running shortly as well.

**Comment by mmachenry** [comment]
I am back from vacation and I've release implicit-0.0.4 to Hackage. It builds on GHC-7.10. There is more to come but enjoy for now. I'm looking into growing this project more as time goes on. If you have any suggestions please let me know.

**Comment by junjihashimoto** [comment]
Thanks!
