### ISSUE TITLE
optparse-applicative version constraint in development setup instructions

### ISSUE THREAD

**Issue by nyx** [colah/ImplicitCAD#124]
In the README you may want to mention specific optparse-applicative version constraint.  After following the development version installation instructions there I got:

```
cabal configure 
Resolving dependencies...
Configuring implicit-0.0.3...
cabal: At least the following dependencies are missing:
optparse-applicative >=0.9.0.0 && <0.10.0
```

Which may be resolved with:

```
cabal install "optparse-applicative<0.10.0"
```

**Comment by julialongtin** [comment]
I think i have this all straightened out, and am using the newest optparse-applicative.
