### ISSUE TITLE
how to start implicit cad from command line

### ISSUE THREAD

**Issue by cobalt-60** [colah/ImplicitCAD#173]
My question is quite simple but very basic.

I have successfully installed it under ubuntu with cabal but I don't know how to start it from the command line.

**Comment by firegurafiku** [comment]
@cobalt-60 

Hi there.
I guess that Cabal have installed the executable as `~/.cabal/bin/extopenscad`. If I'm right, you can run it via full name or add `~/.cabal/bin` into your user's `PATH` instead.

**Comment by cobalt-60** [comment]
Thx, it's exactly like this.
I've symlinked the executable to my ~/bin folder and now everything works fine :-)

Regards, Joerg
