### ISSUE TITLE
Incompatibility: numbers without digit to the left of the decimal not accepted by parser

### ISSUE THREAD

**Issue by Cookshak** [colah/ImplicitCAD#176]
I've downloaded SCAD models that have numbers that begin with a decimal point, for example:
a = .5;

I don't love the style, but OpenSCAD accepts it and interprets it as expected. It seems like this should also be accepted by Extopenscad.

**Comment by Cookshak** [comment]
This issue is the same as #167 so I'll close it.

**Comment by firegurafiku** [comment]
@Cookshak 
How about creating and adding a "duplicate" label?

**Comment by Cookshak** [comment]
Looks like I can't edit the set of labels, since I don't own the repo. This repo doesn't have a duplicate label, currently.
