### ISSUE TITLE
Link in the FAQ is relative

### ISSUE THREAD

**Issue by Moredread** [colah/ImplicitCAD#183]
The Link to www.implicitcad.org in the FAQ is relative and doesn't work correctly.

**Comment by julialongtin** [comment]
This is fixed in the DEV site at http://implicit.faikvm.com/, and will be rolled into production shortly.

**Comment by julialongtin** [comment]
ok, so the fix isn't working. as dev has become prod, this will have to wait for me to create a new dev site, before i can try to fix it again.

**Comment by julialongtin** [comment]
fixed.
