### ISSUE TITLE
Broken mesh output

### ISSUE THREAD

**Issue by tolomea** [colah/ImplicitCAD#19]
This scad file:

difference() {
    sphere(20);
    cylinder(r=17, h=100, center = true);
}

produces non manifold output, here's the admesh output:

================= Results produced by ADMesh version 0.95 ================
Input file         : mesh_death.stl
File type          : ASCII STL file
Header             : solid ImplictCADExport
============== Size ==============
Min X = -20.000000, Max X =  20.000000
Min Y = -20.000000, Max Y =  20.000000
Min Z = -10.252552, Max Z =  10.252552
========= Facet Status ========== Original ============ Final ====
Number of facets                 : 13184               12864
Facets with 1 disconnected edge  :   328                   0
Facets with 2 disconnected edges :    36                   0
Facets with 3 disconnected edges :     0                   0
Total disconnected facets        :   364                   0
=== Processing Statistics ===     ===== Other Statistics =====
Number of parts       :     1        Volume   :  4499.025879
Degenerate facets     :   560
Edges fixed           :     0
Facets removed        :   560
Facets added          :   240
Facets reversed       : 24867
Backwards edges       :   198
Normals fixed         : 12864

**Comment by julialongtin** [comment]
Have you tried a more modern version? while ImplicitCAD is built around the concept of an aproxable representation (as in, there is no perfect answer, but you can request how close to get), we should not be kicking out non-manifold objects.

**Comment by TLC123** [comment]
Its working better now. Still Marching Cubes at its best has inherent limits in mesh quality. Whats needed is a proper feature preserving meshing algorithm like "Dual Contour" or at least "Extended Marching Cubes"

**Comment by jakobdalsgaard** [comment]
Been seeing some of this too; I really like the speed of implicitcad, but it seems incapable of making thin shells by use of difference, such as:

```difference () {
  sphere(r=100);
  sphere(r=98);
  translate([-100, -100,0]) cube(size=[200,200,100]);
}```

Openscad does fine with above. I'd love to take a look at fixing this -- if someone could point me in direction of the right files...
 
![screen shot 2018-01-17 at 1 48 45 pm](https://user-images.githubusercontent.com/11958058/35043506-2f98c1d6-fb8d-11e7-8b02-3aa3240dba1b.png)

**Comment by julialongtin** [comment]
Agreed, this is quite annoying. have you tried dialing up the resolution?

**Comment by julialongtin** [comment]
Added the given example as example15.scad... and fixed what i hope is the last bug in the engine.

juri@qemuhost:~/ImplicitCAD/ImplicitCAD-current$ admesh Examples/example15.stl 
ADMesh version 0.98.3, Copyright (C) 1995, 1996 Anthony D. Martin
ADMesh comes with NO WARRANTY.  This is free software, and you are welcome to
redistribute it under certain conditions.  See the file COPYING for details.
Opening Examples/example15.stl
Checking exact...
All facets connected.  No nearby check necessary.
No unconnected need to be removed.
No holes need to be filled.
Checking normal directions...
Checking normal values...
Calculating volume...
Verifying neighbors...

================= Results produced by ADMesh version 0.98.3 ================
Input file         : Examples/example15.stl
File type          : Binary STL file
Header             : 
============== Size ==============
Min X = -19.960455, Max X =  19.960455
Min Y = -19.960455, Max Y =  19.960455
Min Z = -10.400242, Max Z =  10.400242
========= Facet Status ========== Original ============ Final ====
Number of facets                 :  5408                5408
Facets with 1 disconnected edge  :     0                   0
Facets with 2 disconnected edges :     0                   0
Facets with 3 disconnected edges :     0                   0
Total disconnected facets        :     0                   0
=== Processing Statistics ===     ===== Other Statistics =====
Number of parts       :     1        Volume   :  4708.353516
Degenerate facets     :     0
Edges fixed           :     0
Facets removed        :     0
Facets added          :     0
Facets reversed       :     0
Backwards edges       :     0
Normals fixed         :     0


Note that it is still possible to get bad meshes when running with +RTSOPTS -N in valgrind's cachegrind mode. I'll keep an eye out for that.

Closing this 6 year old issue.
