### ISSUE TITLE
website installation page has buttons to get binaries, but they don't work

### ISSUE THREAD

**Issue by lisaicenm** [colah/ImplicitCAD#196]

**Comment by osbock** [comment]
this is still true

**Comment by osthafen** [comment]
still true - and the links (disabled via css) are dead:

http://www.implicitcad.org/assets/extopenscad-mac
http://www.implicitcad.org/assets/extopenscad-linux-64
http://www.implicitcad.org/assets/extopenscad-windows-64

**Comment by reedrs** [comment]
The dead links are still there.

**Comment by julialongtin** [comment]
Removing these links, as there seems to not be enough community interest to build for these platforms.
