### ISSUE TITLE
Previews?

### ISSUE THREAD

**Issue by l29ah** [colah/ImplicitCAD#200]
Or, as implicitcad currently doesn't do anything like this, what do people use to view STL files? It seems like importing it in openscad and refreshing it manually on updates would be kinda clumsy and overkill.

**Comment by julialongtin** [comment]
I use meshlab. ;)

**Comment by julialongtin** [comment]
there is also a qt wrapper being called 'explicitcad' in development. stay tuned. ;)

**Comment by rvt** [comment]
I was wondering if a visual studio code plugin would be easy to make. It has all the tooling and a song viewer already exists.

**Comment by julialongtin** [comment]
I added a Tools.md. Feel welcome to PR against it, if you find other tools useful.
