### ISSUE TITLE
rotate() is surprisingly slow

### ISSUE THREAD

**Issue by l29ah** [colah/ImplicitCAD#202]
```
$res = 1;
cylinder(100);
```
2.18s user 1.68s system 238% cpu 1.623 total

```
$res = 1;
rotate([0, 90, 0])
	cylinder(100);
```
393.73s user 191.56s system 232% cpu 4:11.45 total

**Comment by julialongtin** [comment]
I've already narrowed this down to being a side effect of one of 8 git
commits, and expect to know what happened sometime today. understanding it
well enough to not just 'undo' it may take the weekend.

**Comment by julialongtin** [comment]
76d4720 is broke.
d62d3a1f8 works.

in case you want to join the hunting. :)

**Comment by julialongtin** [comment]
in fact, could you check those two revisions, to make sure i'm hunting the
same bug you are?

**Comment by l29ah** [comment]
Nah, d62d3a1f8c738efd9575849b56517a56091e83cb still takes much time (and then killed by oom_kill for taking over 6GB of RAM, unlike master).

**Comment by julialongtin** [comment]
OK. two separate bugs. can you ballpark some "worked on commit XXX, broken
on commit YYY", while i finish hunting the performance regression i'm
currently fighting?

Julia Longtin

**Comment by l29ah** [comment]
cca173e93e3a748d82c855e22efbc958346d89b8 is the earliest i could test w/o diving into ghc incompatibilities, and it consumes all the RAM there as well.

**Comment by l29ah** [comment]
I've noticed the rotation produces a suboptimal bounding box: `In box ((-173.20508075688772,-173.20508075688772,-173.20508075688772),(173.20508075688772,173.20508075688772,173.20508075688772))`.
I wonder if it affects performance in any way.

**Comment by julialongtin** [comment]
oh, it sure will. increases the area that needs raytracing.
a better implementation of the bounding box for simple rotates would help.
