### ISSUE TITLE
There is a way to import external modules

### ISSUE THREAD

**Issue by onekk** [colah/ImplicitCAD#206]
Sorry for the inconvenience, but a quick search in the Docs on the site lead me to nothing.

I want to reuse some modules and in Openscad (Sorry but I'm new in ImplicitCAD) I can import them using use<path to the module> but when running it through extopenscad it raise an error about

`unexpected "<"`

There are some syntax differences

Plus the only docs are those in implicitcad docs ?

Many Thanks in advance and best regards.

Carlo D.

**Comment by julialongtin** [comment]
include <module.name>; seems to work fine to me. :)

If you want to see how it works, check out current master, and look at Examples/example23.escad
