### ISSUE TITLE
cube(20); and cube([10,20,30]); both produce no geometry 

### ISSUE THREAD

**Issue by kliment** [colah/ImplicitCAD#216]
Creating a file that consists entirely of cube(20); or cube([10,20,30]);, extopenscad reports "No objects to render". sphere(20); works fine, as does cylinder(r=5,h=10);.

**Comment by rvt** [comment]
You need to use a size param:
cube(size=[4,7,9]);

**Comment by l29ah** [comment]
dae1bd8b042fb942cc100a94355a95cc3b3e5ba7 is the first bad commit

**Comment by julialongtin** [comment]
Welp, that's embarassing. Thank you, Sergey. Fixed in f5139e1 . also added
an example to Examples/ so a revision will be easier to spot.
