### ISSUE TITLE
export gcode directly from ImplicitCAD

### ISSUE THREAD

**Issue by dimitre** [colah/ImplicitCAD#218]
is it possible? I've been trying with
```
~/.cabal/bin/extopenscad -f ngc 2.escad
```
or
```
~/.cabal/bin/extopenscad -f gcode 2.escad
```

and it returns
```
Unrecognized 3D format: GCode
```
Thank you

**Comment by julialongtin** [comment]
ImplicitCAD is not a slicer, but i'm going to leave this open... because
i've been working on a slicer, and will be releasing it after the next
ImplicitCAD release. stay tuned!

**Comment by dimitre** [comment]
Excellent. I've just asked because I think one of the original purposes of the project was to be able to slice without triangulation phase which would result in the best raster for "inifinite resolution" files.

**Comment by julialongtin** [comment]
https://github.com/julialongtin/slicer

It's horrible, but i'm slowly bringing it up to the level of badness of implicitcad.

**Comment by julialongtin** [comment]
https://github.com/julialongtin/hslice

moved it, and have done a lot of work on it. not up to implicitcad standards, but i'm closing this issue.
