### ISSUE TITLE
Binary unavailaible on the website and build fails

### ISSUE THREAD

**Issue by Alkeryn** [colah/ImplicitCAD#222]
Tried to build on arch linux
cabal can't build, i get a succesion of deps build failed because depends of another that failed to build /shrug

**Comment by julialongtin** [comment]
Can i get the logs of your failed build?

**Comment by reedrs** [comment]
I am having the same problem. ghc 8.6.5, cabal-install 2.4.0.0
[cabal.log](https://github.com/colah/ImplicitCAD/files/3389266/cabal.log)

**Comment by julialongtin** [comment]
Have you tried the new makefile for handling cabal 3?

**Comment by Danmou** [comment]
I created a package for ImplicitCAD on AUR, in case it's useful for anyone: https://aur.archlinux.org/packages/implicitcad/

**Comment by julialongtin** [comment]
Added the package to the website. closing issue.
