### ISSUE TITLE
OpenSCAD cylinder and sphere don't accept diameter (d, d1, d2) parameters

### ISSUE THREAD

**Issue by Digital-Monk** [colah/ImplicitCAD#242]
Low priority, because it's easy enough to specify radius instead.  But some kind of warning output would be useful.  For me, spheres just failed to generate anything, and cylinders used a very small radius.

**Comment by julialongtin** [comment]
I'll take a look at this as well. thank you for the report!

**Comment by julialongtin** [comment]
The newer version should have warned you, but.. I've added these, as well. give them a shot!

**Comment by Digital-Monk** [comment]
I'm probably messing up something with the build process...  Did a `git pull`, and now `git log` shows that I'm at  8cb3a93a23541, which should be the newest.

I tried `cabal install`, which seemed to work, but afterwards extopenscad still didn't recognize `d` for `sphere()` or `d1` and `d2` for `cylinder`.

Assumed I did something wrong with cabal, erased the extopenscad binary, tried `cabal build` (huge log, several warnings, no errors) followed by `cabal install`.  Same result.

Sorry to be such a noob with cabal, but should I be doing something else to build with the new code I pulled?

**Comment by julialongtin** [comment]
whoops. typo. try now. :D

**Comment by Digital-Monk** [comment]
Looks good!  And cool that there's a new release!  This is so much nicer than trying to manually fillet things in OpenSCAD...  (I know there's a LOT more to ImplicitCAD than that, but that's the immediate killer feature for my simplistic mechanical designs)
