### ISSUE TITLE
linear_extrude should support XY-scaling

### ISSUE THREAD

**Issue by mietek** [colah/ImplicitCAD#268]
It would be nice if `linear_extrude` accepted a `scale : ℝ → (ℝ, ℝ)` argument that would compute the scale factor for each of the two XY-dimensions separately.

**Comment by FlyingGaz** [comment]
One question that remains to be solved is the type of the scale parameter in `extrudeRM` and the constructor `ExtrudeRM` (Haskell API).

Right now the scale parameter is `Either ℝ (ℝ -> ℝ)`, but going forward we need 3 variants:
- constant `ℝ`
- constant `ℝ2`
- function `ℝ -> Either ℝ ℝ2`

I came up with two possible solutions:
- `Either (Either ℝ ℝ2) (ℝ -> Either ℝ ℝ2)`
- `data ExtrudeScale = C1 ℝ | C2 ℝ2 | F (ℝ -> Either ℝ ℝ2)` (or a generalized name in case we want to reuse the type)

Let me know, what you think and I'll make a proper pull request.

**Comment by mietek** [comment]
I would suggest fully unnesting the nested sum type:
* `data ExtrudeScale = C1 ℝ | C2 ℝ2 | F1 (ℝ -> ℝ) | F2 (ℝ -> ℝ2)`

**Comment by FlyingGaz** [comment]
Unnesting the function is currently not possible, because the extopenscad parser doesn't evaluate the type of a function. Type errors are delayed until [runtime](https://github.com/colah/ImplicitCAD/blob/dd53cd13270f3da3bdeff221ae28ca6bf2d0119e/Graphics/Implicit/ExtOpenScad/Util/OVal.hs#L103).

**Comment by mietek** [comment]
Well, then I would go with your `data ExtrudeScale`.
