### ISSUE TITLE
Introduce a vector type

### ISSUE THREAD

**Issue by isovector** [colah/ImplicitCAD#286]
Today, `implicit` treats all positions (and rotations :scream:) as tuples of `Double`. The library would be significantly more user-friendly if it were to adopt the `V2` and `V3` types from `linear`, or otherwise provide explicit types for positions. The benefits are numerous:

1. Support for the `Num` class, allowing us to perform basic arithmetic, as well as gain access to `fromInteger`
2. Support for `Functor`, which would alleviate the need for things like `both` and `allthree`
3. Allow users to bring in their entire understanding of linear algebra when modeling shapes. For example, I don't trust the current rotation functions, because I don't have any intuition behind the composition of euler angles, but I know exactly how multiplication of rotation matrices works.

Furthermore, I suspect we'd get interesting behavior from `implicit` itself if the field weren't fixed to `Double`.

**Comment by julialongtin** [comment]
no strong argument against. There are some places where there are workarounds that depend on the type, but i'm sure you'll stumble across them. mind putting together a short PR?
