### ISSUE TITLE
function variable binding is not consistent with openscad

### ISSUE THREAD

**Issue by tolomea** [colah/ImplicitCAD#29]
In particular it looks like openscad is binding free variables at module invocation and implicitcad at module definition.

This scad:

function bob(x) = x*y;
y=10;
sphere(bob(1));

produces a sphere of size 10 in openscad and the following error in implicitcad:

Module sphere failed with the following messages:
  error in computing value for arugment r: Can't multiply objects of types Number and Undefined.
Nothing to render

This scad:

y=10;
function bob(x) = x*y;
y=1;
sphere(bob(1));

produces a sphere of size 1 in openscad and a sphere of size 10 in implicitcad.

I'm not sure how useful this behavior is, but if we were not going to support it we would need to come up with a good error message that catches both cases.

**Comment by julialongtin** [comment]
I'm actually good with leaving this in the type 3 state for now, but I'd prefer to move this to type 1.

**Comment by julialongtin** [comment]
A recent patch has changed this from a type 3, to at least a type 2, if not a type 1 error:

```
// Example8.escad -- variable assignment in loops.
a = 5;
for (c = [1, 2, 3]) {
        echo(c);
        a = a*c;
        echo(a);
}
```

now produces:
```
Warning at line 5, column 9: redefining already defined variable: "a"
Warning at line 5, column 9: redefining already defined variable: "a"
Warning at line 5, column 9: redefining already defined variable: "a"
TextOut at line 4, column 9: 1.0
TextOut at line 6, column 9: 5.0
TextOut at line 4, column 9: 2.0
TextOut at line 6, column 9: 10.0
TextOut at line 4, column 9: 3.0
TextOut at line 6, column 9: 30.0
```

Errors in general are in much better shape now. Anyone care to discuss what warnings/errors we would want to close this issue?

**Comment by julialongtin** [comment]
Giving this two more weeks, then closing.
