### ISSUE TITLE
implicitcad.org is unreachable

### ISSUE THREAD

**Issue by tymokvo** [colah/ImplicitCAD#383]
Hello! Just wanted to alert you that http://www.implicitcad.org website seems to be unreachable. 

`dig` shows a valid DNS record, but `curl` is returning `No route to host`.

**Comment by julialongtin** [comment]
yeah, we're having trouble with our VPN provider. i expect it will get straightened out tomorrow. thanks tho! :)

**Comment by julialongtin** [comment]
fixed! thanks!

**Comment by tymokvo** [comment]
woo!
