### ISSUE TITLE
Support for $f_ variables

### ISSUE THREAD

**Issue by cbiffle** [colah/ImplicitCAD#39]
Consider the code

```
circle(r = R, $fn = 6);
```

In OpenSCAD, this is a regular hexagon inscribed inside a circle of radius R.  In ImplicitCAD (as of today) it's a circle and a compile warning.

OpenSCAD global variables (starting with dollar signs) are a curious variety of scoped globals, which are in effect passed implicitly to every module and function.  If I invoke a module M like so:

```
M($fn = 10);
```

it overrides the value of `$fn` _inside_ M and any sub-modules it invokes -- unless they override `$fn` themselves.

While I often use these globals to adjust quality for 3D printing -- both to add vertices to overly chunky parts, and to remove them to speed up printing -- they're not purely cosmetic.  I use `$fn` specifically for the regular-polygon-in-a-circle case described above, to model things like hex nuts.

In the interest of source compatibility with OpenSCAD I think these are worth implementing, even though they're weird.

**Comment by julialongtin** [comment]
I'm good with these functions continuing to not be implemented or passed. this feature of openscad is quirky.
