### ISSUE TITLE
2D svg not importing at correct scale into Inkscape 0.48

### ISSUE THREAD

**Issue by chuck-h** [colah/ImplicitCAD#83]
Seems to need a viewBox entry
http://opensourceecology.org/wiki/TorchTableToolChainTesting#convert_svg_scale

Chuck

**Comment by mmachenry** [comment]
I have fixed this in a recent pull request. I will probably be closing this issue unless you verify that there is still a problem for you. But it's been three years since your last comment, so maybe you're gone. :)

**Comment by mmachenry** [comment]
Without further comment I'll assume this issue is fixed.
